var annotated_dup =
[
    [ "AnimationOverrides", "classAnimationOverrides.html", "classAnimationOverrides" ],
    [ "CharacterAttribute", "structCharacterAttribute.html", "structCharacterAttribute" ],
    [ "EventHandler", "classEventHandler.html", "classEventHandler" ],
    [ "GameClock", "classGameClock.html", "classGameClock" ],
    [ "InventoryItem", "structInventoryItem.html", "structInventoryItem" ],
    [ "InventoryManager", "classInventoryManager.html", "classInventoryManager" ],
    [ "Item", "classItem.html", "classItem" ],
    [ "ItemCodeDescriptionAttribute", "classItemCodeDescriptionAttribute.html", null ],
    [ "ItemCodeDescriptionDrawer", "classItemCodeDescriptionDrawer.html", "classItemCodeDescriptionDrawer" ],
    [ "ItemDetails", "classItemDetails.html", "classItemDetails" ],
    [ "ItemNudge", "classItemNudge.html", "classItemNudge" ],
    [ "ItemPickup", "classItemPickup.html", "classItemPickup" ],
    [ "MovementAnimationParameterControl", "classMovementAnimationParameterControl.html", "classMovementAnimationParameterControl" ],
    [ "ObscuringItemFader", "classObscuringItemFader.html", "classObscuringItemFader" ],
    [ "Player", "classPlayer.html", "classPlayer" ],
    [ "PlayerAnimationTest", "classPlayerAnimationTest.html", "classPlayerAnimationTest" ],
    [ "SceneControllerManager", "classSceneControllerManager.html", "classSceneControllerManager" ],
    [ "SceneTeleport", "classSceneTeleport.html", "classSceneTeleport" ],
    [ "Settings", "classSettings.html", "classSettings" ],
    [ "SingletonMonobehaviour", "classSingletonMonobehaviour.html", "classSingletonMonobehaviour" ],
    [ "SO_AnimationType", "classSO__AnimationType.html", "classSO__AnimationType" ],
    [ "SOItemList", "classSOItemList.html", "classSOItemList" ],
    [ "SwitchConfineBoundingShape", "classSwitchConfineBoundingShape.html", "classSwitchConfineBoundingShape" ],
    [ "Tags", "classTags.html", "classTags" ],
    [ "TimeManager", "classTimeManager.html", "classTimeManager" ],
    [ "TriggerObscuringItemFader", "classTriggerObscuringItemFader.html", "classTriggerObscuringItemFader" ],
    [ "UIInventoryBar", "classUIInventoryBar.html", "classUIInventoryBar" ],
    [ "UIInventorySlot", "classUIInventorySlot.html", "classUIInventorySlot" ],
    [ "UIInventoryTextBox", "classUIInventoryTextBox.html", "classUIInventoryTextBox" ]
];